variables:
  THEWORKDIR: /transient-builds
  DEFAULT_NEWSIZE: 16G
  XZ_COMPRESSION_LEVEL: 9

jobs:

- job: Snapping
  pool:
    vmImage: '$(PIPELINEIMAGE)'
  timeoutInMinutes: 120
  strategy:
    maxParallel: 4
    matrix:
      
      'classic 20.04':
        confinement: classic
        PIPELINEIMAGE: ubuntu-20.04
      'strict 20.04':
        confinement: strict
        PIPELINEIMAGE: ubuntu-20.04

      # 'classic 22.04':
      #   confinement: classic
      #   PIPELINEIMAGE: ubuntu-22.04
      # 'strict 22.04':
      #   confinement: strict
      #   PIPELINEIMAGE: ubuntu-22.04

  steps:
  - script: |
      set -eu; set -o pipefail
      script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
      Say --Reset-Stopwatch
      echo "CPU: $(Get-CpuName)"
      printenv | sort;
    displayName: 'Variables'

  - script: |
      set -eu; set -o pipefail
      echo "CPU: $(Get-CpuName)"
      sudo apt-get update -qq
      # time sudo snap install multipass
      time sudo snap install snapcraft --channel=8.x/stable --classic
    displayName: 'Provisioning'

  - script: |
      set -eu; set -o pipefail
      echo "CPU: $(Get-CpuName)"
      Say --Reset-Stopwatch
      cd snap-source
      bash -e download-binaries.sh # need for VERSION file only
      bash -e patch-snapcraft.sh "snap/snapcraft.yaml" "confinement" "$CONFINEMENT"
      bash -e build-snap.sh
    displayName: "Build $(CONFINEMENT)"

  - script: |
      set -eu; set -o pipefail
      echo "CPU: $(Get-CpuName)"
      Say --Reset-Stopwatch
      cd snap-source

      classicArg="--devmode"; test "$CONFINEMENT" = "classic" && classicArg="--dangerous --classic"
      Say "INSTALL ARGUMENTS: [$classicArg]"
      time sudo snap install w3diskmark*.snap $classicArg
      time sudo snap set w3diskmark http.port=5555
      time sudo snap restart w3diskmark 
      # bash -c w3diskmark &
      sleep 10
      Say "ALL THE PROCESSES"
      sudo ps -aux
      Say "SNAP PROCESSES"
      sudo ps -aux | grep Universe
      Say "SNAP SERVICES"
      sudo snap services
      curl -I http://localhost:5555
      for ((i=1; i<=12; i++)); do
        # Say "Restart w3diskmark [$i]"
        port=$((i+5555))
        time sudo snap set w3diskmark http.port=5555
        sudo rm -rf "/root/snap/w3diskmark/common"/*
        sudo rm -rf "/root/snap/w3diskmark/~current"/*
        sudo rm -rf "/var/snap/w3diskmark/common"/*
        sudo rm -rf "/var/snap/w3diskmark/~current"/*
        time sudo snap restart w3diskmark && Say "Success Restart w3diskmark [$i]" || Say --Display-As=Error "Failed Restart w3diskmark [$i]"
        sleep 3
      done
    displayName: 'Smoke Test'

  - script: |
      set -eu; set -o pipefail
      echo "CPU: $(Get-CpuName)"
      time sudo snap logs -n=all w3diskmark.service |& tee $SYSTEM_ARTIFACTSDIRECTORY/w3diskmark.service.log
    condition: succeededOrFailed()      
    displayName: 'Snap Daemon Logs'

  - script: |
      set -eu; set -o pipefail
      echo "CPU: $(Get-CpuName)"
      Say --Reset-Stopwatch
      sudo chown -R $USER $HOME
      find $HOME -name '*.log' -exec cp -v -f {} $SYSTEM_ARTIFACTSDIRECTORY \;

      cd snap-source

      for f in $(ls -1 *.snap); do
        # cat $f | xz -z -1 > $SYSTEM_ARTIFACTSDIRECTORY/$f.xz
        cp -v $f $SYSTEM_ARTIFACTSDIRECTORY/
      done


    condition: succeededOrFailed()
    displayName: 'Compress artifact image'

  - task: PublishBuildArtifacts@1
    condition: succeeded()
    displayName: 'Publish Final'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: 'Succeeded $(Agent.JobName)'

  - task: PublishBuildArtifacts@1
    condition: failed()
    displayName: 'Publish Errors'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: 'Failed $(Agent.JobName)-$(Build.BUILDNUMBER)'
