name: w3diskmark
base: core20
version: '0.1'
summary: Cross-Platform Disk Benchmark
grade: devel
epoch: 1
# Strict: Access to the path '/proc/mounts' is denied.
confinement: strict
description: |
  w3diskmark is backed by fio, provides rich Material based UI using built-in http server, supports wide range of browsers and linux distributions.

parts:
  w3diskmark:
    override-pull: |
      set -eux
      echo "BEFORE: "$(ls "$SNAPCRAFT_PART_SRC")
      script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
      arch="$SNAPCRAFT_TARGET_ARCH";
      if [[ "$arch" == "amd64" ]]; then arch=x64; elif [[ "$arch" == "armhf" ]]; then arch=arm; fi
      url="https://github.com/devizer/w3top-bin/releases/latest/download/w3top-linux-$arch.tar.gz"
      copy="$(mktemp -t w3top-$arch.XXXXXXXXX)"
      echo "Downloading [$url] for the [$SNAPCRAFT_TARGET_ARCH] arch as [$copy]"
      try-and-retry curl -ksfSL -o "$copy" "$url"
      pushd "$SNAPCRAFT_PART_SRC"
        tar xzf "$copy"
        rm -f "$copy"
        try-and-retry curl -ksfSL -o ./w3diskmark "https://raw.githubusercontent.com/devizer/w3diskmark/main/snap-source/w3diskmark"
        chmod +x ./w3diskmark
      popd
      # SKIP: snapcraftctl pull
      echo "AFTER: "$(ls "$SNAPCRAFT_PART_SRC")
      ver="$(cat VERSION)"
      echo "VERSION IS [$ver] (2.41+)"
      snapcraftctl set-version "$ver"
      echo "KERNEL IS $(uname -r)"
      printenv | sort | grep "SNAP\|SNAPCRAFT" || true
    plugin: dump
    source: # pull ignored
      - to amd64: ./bin-x64/
      - to arm64: ./bin-arm64/
      - to armhf: ./bin-arm/
    stage-packages:
      - ca-certificates
      # - libicu60
      # - libssl1.1
      - liblttng-ust0
      # - fio

      # curl ca-certificates libkrb5-3 zlib1g libicu60 libssl1.0.0 libssl1.1 libunwind8 libuuid1 liblttng-ust0

apps:
  service:
    command: ./w3diskmark
    daemon: simple
    stop-mode: sigint-all
    install-mode: enable
    refresh-mode: restart
    restart-condition: on-failure
    restart-delay: 20s
    plugs: 
      - network
      - network-bind
      - hardware-observe
      - cpu-control
      - cifs-mount
      - block-devices
      - mount-observe
      - network-manager-observe
      - network-observe
      - optical-drive
      - physical-memory-observe
      - raw-usb
      - raw-volume
      - removable-media
      - scsi-generic
      - sd-control
      - system-observe
      - upower-observe



