#!/usr/bin/env bash
# This script propogates builtin private libssl v1.1.1 if shared libssl v1.1.* is absent
set -e
set -u
pushd `dirname $0` > /dev/null; ScriptPath=`pwd`; popd > /dev/null


if [[ "${1:-}" == "--flush-state" ]]; then
  if [[ -z "${SNAP_DATA:-}" ]] || [[ -z "${SNAP_USER_DATA:-}" ]]; then
    echo "Flush state is not available outside of snap";
    exit 0;
  fi
  sizeSystem="$(du -h --max-depth 0 "$SNAP_DATA" | awk '{print $1}')"
  sizeUser="$(du -h --max-depth 0 "$SNAP_USER_DATA" | awk '{print $1}')"
  echo "Flush state at $SNAP_DATA ($sizeSystem) and $SNAP_USER_DATA ($sizeUser)"
  rm -rf $SNAP_DATA/*;
  rm -rf $SNAP_USER_DATA/*;
  exit 0
fi

if [[ "${1:-}" == "--vars" ]]; then
  echo "VARS. w3diskmark version $("$ScriptPath/Universe.W3Top" --version)"
  echo "____"
  printenv | sort 
  exit 0
fi

if [[ "${1:-}" == "--version" ]]; then
  "$ScriptPath/Universe.W3Top" --version
  exit 0
fi

if [[ ! -f "$ScriptPath/Universe.W3Top" ]]; then echo ERROR: publish the project first; exit 1; fi

export HTTP_PORT="$(snapctl get http.port)"
export HTTP_PORT="${HTTP_PORT:-5050}"
# echo "PORT IS [$HTTP_PORT]"
export HTTP_HOST="${HTTP_HOST:-0.0.0.0}"
export RESPONSE_COMPRESSION="${RESPONSE_COMPRESSION:-True}"
export DUMPS_ARE_ENABLED="${DUMPS_ARE_ENABLED:-False}"

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
export BLOCK_DEVICE_VISIBILITY_THRESHOLD=2048
export FORCE_HTTPS_REDIRECT=False

export PID_FILE_FULL_PATH=/var/run/w3top.pid
export ASPNETCORE_URLS="http://$HTTP_HOST:$HTTP_PORT"
export INSTALL_DIR="$ScriptPath"

if [[ -n "$(command -v ldconfig)" ]] && [[ -z "$(ldconfig -p | grep libssl.so.1.1)" ]]; then
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}:$ScriptPath/optional/libssl-1.1"
fi

pushd "$ScriptPath" >/dev/null
./Universe.W3Top
popd >/dev/null
